/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jairo.gest.gui;


import com.jairo.gest.usuarios.Cuenta;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;


/**
 *
 * @author Jairo
 */
public class VentanaVerCuenta extends javax.swing.JFrame {

    private Cuenta cuenta;
    private String usuario;
    private int mouseX, mouseY;
    public VentanaVerCuenta(String usuario, Cuenta cuenta) {
        setLookAndFeel();
        initComponents();
        
        this.usuario = usuario;
        this.cuenta = cuenta;
        mensaje.setVisible(false);
        
        setUsrInfo();
        setCuentaInfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bg2 = new javax.swing.JPanel();
        cuentaInfPanel = new javax.swing.JPanel();
        cuentaInfLbl = new javax.swing.JLabel();
        nomUsrLbl = new javax.swing.JLabel();
        nomUsrTxtBox = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        contLbl = new javax.swing.JLabel();
        separador3 = new javax.swing.JSeparator();
        descCuentaLbl = new javax.swing.JLabel();
        descCuentaTxtBox = new javax.swing.JTextField();
        uriLbl = new javax.swing.JLabel();
        uriTxtBox = new javax.swing.JTextField();
        separador4 = new javax.swing.JSeparator();
        contTextBox = new javax.swing.JPasswordField();
        ojoPanel = new javax.swing.JPanel();
        ojo = new javax.swing.JLabel();
        ojoPanel1 = new javax.swing.JPanel();
        ojo1 = new javax.swing.JLabel();
        usrInfo = new javax.swing.JPanel();
        usrInfoLbl = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        bar = new javax.swing.JPanel();
        exitB = new javax.swing.JPanel();
        exitLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(203, 182, 184));
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.setPreferredSize(new java.awt.Dimension(737, 467));

        bg2.setBackground(new java.awt.Color(31, 31, 31));

        cuentaInfPanel.setBackground(new java.awt.Color(255, 255, 255));
        cuentaInfPanel.setFocusable(false);
        cuentaInfPanel.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        cuentaInfLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cuentaInfLbl.setText("Cuenta: Cuenta");

        nomUsrLbl.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        nomUsrLbl.setText("Nombre de usuario");

        nomUsrTxtBox.setEditable(false);
        nomUsrTxtBox.setBackground(new java.awt.Color(255, 255, 255));
        nomUsrTxtBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nomUsrTxtBox.setText("Nombre de usuario de la cuenta");
        nomUsrTxtBox.setBorder(null);
        nomUsrTxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomUsrTxtBoxFocusGained(evt);
            }
        });
        nomUsrTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomUsrTxtBoxActionPerformed(evt);
            }
        });

        separador1.setForeground(new java.awt.Color(0, 0, 0));

        separador2.setForeground(new java.awt.Color(0, 0, 0));

        contLbl.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        contLbl.setText("Contraseña");

        separador3.setForeground(new java.awt.Color(0, 0, 0));

        descCuentaLbl.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        descCuentaLbl.setText("Descripción");

        descCuentaTxtBox.setEditable(false);
        descCuentaTxtBox.setBackground(new java.awt.Color(255, 255, 255));
        descCuentaTxtBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        descCuentaTxtBox.setText("Descripción de la cuenta");
        descCuentaTxtBox.setBorder(null);
        descCuentaTxtBox.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        descCuentaTxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descCuentaTxtBoxFocusGained(evt);
            }
        });
        descCuentaTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descCuentaTxtBoxActionPerformed(evt);
            }
        });

        uriLbl.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        uriLbl.setText("URI");

        uriTxtBox.setEditable(false);
        uriTxtBox.setBackground(new java.awt.Color(255, 255, 255));
        uriTxtBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        uriTxtBox.setText("URI");
        uriTxtBox.setBorder(null);
        uriTxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uriTxtBoxFocusGained(evt);
            }
        });
        uriTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uriTxtBoxActionPerformed(evt);
            }
        });

        separador4.setForeground(new java.awt.Color(0, 0, 0));

        contTextBox.setEditable(false);
        contTextBox.setBackground(new java.awt.Color(255, 255, 255));
        contTextBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        contTextBox.setText("jPasswordField1");
        contTextBox.setBorder(null);
        contTextBox.setEchoChar('*');

        ojoPanel.setBackground(new java.awt.Color(255, 255, 255));

        ojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jairo\\Documents\\NetBeansProjects\\GestorContrasenias\\src\\main\\java\\com\\jairo\\gest\\gui\\assets\\ojito.png")); // NOI18N
        ojo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ojoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ojoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ojoPanelLayout = new javax.swing.GroupLayout(ojoPanel);
        ojoPanel.setLayout(ojoPanelLayout);
        ojoPanelLayout.setHorizontalGroup(
            ojoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ojo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        ojoPanelLayout.setVerticalGroup(
            ojoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ojo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        ojoPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ojo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ojo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ojo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jairo\\Documents\\NetBeansProjects\\GestorContrasenias\\src\\main\\java\\com\\jairo\\gest\\gui\\assets\\copiar.png")); // NOI18N
        ojo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ojo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ojo1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ojo1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ojo1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ojo1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout ojoPanel1Layout = new javax.swing.GroupLayout(ojoPanel1);
        ojoPanel1.setLayout(ojoPanel1Layout);
        ojoPanel1Layout.setHorizontalGroup(
            ojoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ojo1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        ojoPanel1Layout.setVerticalGroup(
            ojoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ojo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout cuentaInfPanelLayout = new javax.swing.GroupLayout(cuentaInfPanel);
        cuentaInfPanel.setLayout(cuentaInfPanelLayout);
        cuentaInfPanelLayout.setHorizontalGroup(
            cuentaInfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentaInfPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(cuentaInfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuentaInfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(descCuentaLbl)
                        .addComponent(descCuentaTxtBox)
                        .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cuentaInfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(uriLbl)
                        .addComponent(uriTxtBox)
                        .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contLbl)
                    .addGroup(cuentaInfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nomUsrLbl)
                        .addComponent(cuentaInfLbl)
                        .addComponent(nomUsrTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                        .addComponent(separador1))
                    .addGroup(cuentaInfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(cuentaInfPanelLayout.createSequentialGroup()
                            .addComponent(contTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ojoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ojoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(separador2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        cuentaInfPanelLayout.setVerticalGroup(
            cuentaInfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentaInfPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuentaInfLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomUsrLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomUsrTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contLbl)
                .addGap(7, 7, 7)
                .addGroup(cuentaInfPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ojoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contTextBox)
                    .addComponent(ojoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uriLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uriTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descCuentaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descCuentaTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        usrInfo.setBackground(new java.awt.Color(255, 255, 255));

        usrInfoLbl.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        usrInfoLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usrInfoLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jairo\\Documents\\NetBeansProjects\\GestorContrasenias\\src\\main\\java\\com\\jairo\\gest\\gui\\assets\\User.png")); // NOI18N
        usrInfoLbl.setText("Usuario");

        javax.swing.GroupLayout usrInfoLayout = new javax.swing.GroupLayout(usrInfo);
        usrInfo.setLayout(usrInfoLayout);
        usrInfoLayout.setHorizontalGroup(
            usrInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usrInfoLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(usrInfoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        usrInfoLayout.setVerticalGroup(
            usrInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usrInfoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        mensaje.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje.setText("Mensaje");

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addComponent(usrInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cuentaInfPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(usrInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensaje)
                        .addGap(20, 20, 20)))
                .addComponent(cuentaInfPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        bar.setBackground(new java.awt.Color(203, 182, 184));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });

        exitB.setBackground(new java.awt.Color(203, 182, 184));
        exitB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBMouseExited(evt);
            }
        });

        exitLbl.setBackground(new java.awt.Color(203, 182, 184));
        exitLbl.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        exitLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLbl.setText("X");
        exitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBLayout = new javax.swing.GroupLayout(exitB);
        exitB.setLayout(exitBLayout);
        exitBLayout.setHorizontalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
        exitBLayout.setVerticalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX , y - mouseY );
    }//GEN-LAST:event_barMouseDragged

    private void exitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitLblMouseClicked

    private void exitLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseEntered
        exitB.setBackground(new Color(210, 51, 105));
    }//GEN-LAST:event_exitLblMouseEntered

    private void exitBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseExited
        exitB.setBackground(new Color(203, 182, 184));
    }//GEN-LAST:event_exitBMouseExited

    private void exitBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseEntered
        exitB.setBackground(new Color(210, 51, 105));
    }//GEN-LAST:event_exitBMouseEntered

    private void exitLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseExited
        exitB.setBackground(new Color(203, 182, 184));
    }//GEN-LAST:event_exitLblMouseExited

    private void nomUsrTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomUsrTxtBoxActionPerformed
        
    }//GEN-LAST:event_nomUsrTxtBoxActionPerformed

    private void nomUsrTxtBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomUsrTxtBoxFocusGained
        
    }//GEN-LAST:event_nomUsrTxtBoxFocusGained

    private void descCuentaTxtBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descCuentaTxtBoxFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_descCuentaTxtBoxFocusGained

    private void descCuentaTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descCuentaTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descCuentaTxtBoxActionPerformed

    private void uriTxtBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uriTxtBoxFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_uriTxtBoxFocusGained

    private void uriTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uriTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uriTxtBoxActionPerformed

    private void ojoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoMouseReleased
        contTextBox.setEchoChar('*');
    }//GEN-LAST:event_ojoMouseReleased

    private void ojoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojoMousePressed
        contTextBox.setEchoChar((char)0);
    }//GEN-LAST:event_ojoMousePressed

    private void ojo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojo1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ojo1MousePressed

    private void ojo1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojo1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ojo1MouseReleased

    private void ojo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojo1MouseClicked
        String str = String.valueOf(contTextBox.getPassword());
        Clipboard clip = Toolkit.getDefaultToolkit()
                             .getSystemClipboard();
        StringSelection strse1 = new StringSelection(str);
        clip.setContents(strse1, strse1);
        
        mensaje.setVisible(true);
        mensaje.setText("Contraseña copiada al portapapeles");
        
    }//GEN-LAST:event_ojo1MouseClicked

    private void ojo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojo1MouseExited
        mensaje.setVisible(false);
    }//GEN-LAST:event_ojo1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVerCuenta("Juanito", new Cuenta(1,1,"","","","",""));
            }
        });
    }
    
    
    private void setCuentaInfo(){
        cuentaInfLbl.setText("Cuenta: " + cuenta.getNomCuenta());
        nomUsrTxtBox.setText(cuenta.getUsrCuenta());
        contTextBox.setText(cuenta.getContCuenta());
        uriTxtBox.setText(cuenta.getUri());
        descCuentaTxtBox.setText(cuenta.getDescCuenta());
    }
    
    private void setUsrInfo(){
        usrInfoLbl.setText(usuario);
    }
    
    private void setLookAndFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVerCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVerCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVerCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVerCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg2;
    private javax.swing.JLabel contLbl;
    private javax.swing.JPasswordField contTextBox;
    private javax.swing.JLabel cuentaInfLbl;
    private javax.swing.JPanel cuentaInfPanel;
    private javax.swing.JLabel descCuentaLbl;
    private javax.swing.JTextField descCuentaTxtBox;
    private javax.swing.JPanel exitB;
    private javax.swing.JLabel exitLbl;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel nomUsrLbl;
    private javax.swing.JTextField nomUsrTxtBox;
    private javax.swing.JLabel ojo;
    private javax.swing.JLabel ojo1;
    private javax.swing.JPanel ojoPanel;
    private javax.swing.JPanel ojoPanel1;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JLabel uriLbl;
    private javax.swing.JTextField uriTxtBox;
    private javax.swing.JPanel usrInfo;
    private javax.swing.JLabel usrInfoLbl;
    // End of variables declaration//GEN-END:variables
}
