/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jairo.gest.gui;


import com.jairo.gest.eliminadores.EliminadorFolder;
import com.jairo.gest.usuarios.Folder;
import com.jairo.gest.usuarios.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Jairo
 */
public class VentanaFolders extends javax.swing.JFrame {

    private Usuario usuario;
    private int mouseX, mouseY;
    public VentanaFolders(Usuario usuario) {
        setLookAndFeel();
        initComponents();
        this.usuario = usuario;
        setTable();
        setUsrInfo();
        setFolders();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bg2 = new javax.swing.JPanel();
        foldPanel = new javax.swing.JPanel();
        foldersLbl = new javax.swing.JLabel();
        foldersSP = new javax.swing.JScrollPane();
        foldersTab = new javax.swing.JTable();
        usrInfo = new javax.swing.JPanel();
        usrInfoLbl = new javax.swing.JLabel();
        verFoldBtn = new javax.swing.JPanel();
        verFoldLbl = new javax.swing.JLabel();
        elimFoldBtn = new javax.swing.JPanel();
        elimFoldLbl = new javax.swing.JLabel();
        crearFoldBtn = new javax.swing.JPanel();
        crearFoldLbl = new javax.swing.JLabel();
        editFoldBtn = new javax.swing.JPanel();
        editFoldLbl = new javax.swing.JLabel();
        bar = new javax.swing.JPanel();
        exitB = new javax.swing.JPanel();
        exitLbl = new javax.swing.JLabel();
        reloadPanel = new javax.swing.JPanel();
        reloadLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(203, 182, 184));
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.setPreferredSize(new java.awt.Dimension(737, 467));

        bg2.setBackground(new java.awt.Color(31, 31, 31));

        foldPanel.setBackground(new java.awt.Color(255, 255, 255));
        foldPanel.setFocusable(false);
        foldPanel.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        foldersLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        foldersLbl.setText("Folders");

        foldersTab.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        foldersTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        foldersTab.setFocusable(false);
        foldersTab.setGridColor(new java.awt.Color(167, 167, 167));
        foldersTab.setRowHeight(30);
        foldersTab.setSelectionBackground(new java.awt.Color(147, 147, 147));
        foldersTab.setSelectionForeground(new java.awt.Color(255, 255, 255));
        foldersTab.setShowHorizontalLines(true);
        foldersTab.getTableHeader().setReorderingAllowed(false);
        foldersSP.setViewportView(foldersTab);
        if (foldersTab.getColumnModel().getColumnCount() > 0) {
            foldersTab.getColumnModel().getColumn(0).setResizable(false);
            foldersTab.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout foldPanelLayout = new javax.swing.GroupLayout(foldPanel);
        foldPanel.setLayout(foldPanelLayout);
        foldPanelLayout.setHorizontalGroup(
            foldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foldPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(foldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foldersSP, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foldersLbl))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        foldPanelLayout.setVerticalGroup(
            foldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foldersLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foldersSP, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        usrInfo.setBackground(new java.awt.Color(255, 255, 255));

        usrInfoLbl.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        usrInfoLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usrInfoLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jairo\\Documents\\NetBeansProjects\\GestorContrasenias\\src\\main\\java\\com\\jairo\\gest\\gui\\assets\\User.png")); // NOI18N
        usrInfoLbl.setText("Usuario");

        javax.swing.GroupLayout usrInfoLayout = new javax.swing.GroupLayout(usrInfo);
        usrInfo.setLayout(usrInfoLayout);
        usrInfoLayout.setHorizontalGroup(
            usrInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usrInfoLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(usrInfoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        usrInfoLayout.setVerticalGroup(
            usrInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usrInfoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        verFoldBtn.setBackground(new java.awt.Color(255, 255, 255));

        verFoldLbl.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        verFoldLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verFoldLbl.setText("Ver Folder");
        verFoldLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        verFoldLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verFoldLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout verFoldBtnLayout = new javax.swing.GroupLayout(verFoldBtn);
        verFoldBtn.setLayout(verFoldBtnLayout);
        verFoldBtnLayout.setHorizontalGroup(
            verFoldBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verFoldLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        verFoldBtnLayout.setVerticalGroup(
            verFoldBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verFoldLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        elimFoldBtn.setBackground(new java.awt.Color(255, 255, 255));

        elimFoldLbl.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        elimFoldLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        elimFoldLbl.setText("Eliminar Folder");
        elimFoldLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elimFoldLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elimFoldLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout elimFoldBtnLayout = new javax.swing.GroupLayout(elimFoldBtn);
        elimFoldBtn.setLayout(elimFoldBtnLayout);
        elimFoldBtnLayout.setHorizontalGroup(
            elimFoldBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elimFoldLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );
        elimFoldBtnLayout.setVerticalGroup(
            elimFoldBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elimFoldLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        crearFoldBtn.setBackground(new java.awt.Color(255, 255, 255));

        crearFoldLbl.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        crearFoldLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearFoldLbl.setText("Crear Folder");
        crearFoldLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearFoldLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearFoldLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crearFoldBtnLayout = new javax.swing.GroupLayout(crearFoldBtn);
        crearFoldBtn.setLayout(crearFoldBtnLayout);
        crearFoldBtnLayout.setHorizontalGroup(
            crearFoldBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearFoldLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        crearFoldBtnLayout.setVerticalGroup(
            crearFoldBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crearFoldLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        editFoldBtn.setBackground(new java.awt.Color(255, 255, 255));

        editFoldLbl.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        editFoldLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editFoldLbl.setText("Editar Folder");
        editFoldLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editFoldLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editFoldLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editFoldBtnLayout = new javax.swing.GroupLayout(editFoldBtn);
        editFoldBtn.setLayout(editFoldBtnLayout);
        editFoldBtnLayout.setHorizontalGroup(
            editFoldBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editFoldLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        editFoldBtnLayout.setVerticalGroup(
            editFoldBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editFoldLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(foldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usrInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addComponent(verFoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(crearFoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editFoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(elimFoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(usrInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verFoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elimFoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearFoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editFoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        bar.setBackground(new java.awt.Color(203, 182, 184));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });

        exitB.setBackground(new java.awt.Color(203, 182, 184));
        exitB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBMouseExited(evt);
            }
        });

        exitLbl.setBackground(new java.awt.Color(203, 182, 184));
        exitLbl.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        exitLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLbl.setText("X");
        exitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBLayout = new javax.swing.GroupLayout(exitB);
        exitB.setLayout(exitBLayout);
        exitBLayout.setHorizontalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        exitBLayout.setVerticalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        reloadPanel.setBackground(new java.awt.Color(203, 182, 184));

        reloadLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jairo\\Documents\\NetBeansProjects\\GestorContrasenias\\src\\main\\java\\com\\jairo\\gest\\gui\\assets\\Reload.png")); // NOI18N
        reloadLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reloadLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout reloadPanelLayout = new javax.swing.GroupLayout(reloadPanel);
        reloadPanel.setLayout(reloadPanelLayout);
        reloadPanelLayout.setHorizontalGroup(
            reloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reloadLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        reloadPanelLayout.setVerticalGroup(
            reloadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reloadLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reloadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reloadPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX , y - mouseY );
    }//GEN-LAST:event_barMouseDragged

    private void exitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitLblMouseClicked

    private void exitLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseEntered
        exitB.setBackground(new Color(210, 51, 105));
    }//GEN-LAST:event_exitLblMouseEntered

    private void exitBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseExited
        exitB.setBackground(new Color(203, 182, 184));
    }//GEN-LAST:event_exitBMouseExited

    private void exitBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseEntered
        exitB.setBackground(new Color(210, 51, 105));
    }//GEN-LAST:event_exitBMouseEntered

    private void exitLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseExited
        exitB.setBackground(new Color(203, 182, 184));
    }//GEN-LAST:event_exitLblMouseExited

    private void verFoldLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verFoldLblMouseClicked
        VentanaVerFolder ventana; 
        Folder f;
        int filaSelec;
        
        filaSelec = foldersTab.getSelectedRow();
        
        if(filaSelec >= 0){
            f = usuario.getFolders().get(filaSelec);
            
            ventana = new VentanaVerFolder(usuario.getUsuario(), usuario.getContM(), f);
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_verFoldLblMouseClicked

    private void crearFoldLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearFoldLblMouseClicked
        VentanaCreaFolder ventana;

        ventana = new VentanaCreaFolder(usuario,this);
        ventana.setVisible(true);
    }//GEN-LAST:event_crearFoldLblMouseClicked

    private void reloadLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadLblMouseClicked
        setFolders();
    }//GEN-LAST:event_reloadLblMouseClicked

    private void elimFoldLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elimFoldLblMouseClicked
        Folder f;
        EliminadorFolder ef;
        int filaSelec;
        
        filaSelec   = foldersTab.getSelectedRow();
        ef          = new EliminadorFolder();
        
        if(filaSelec >= 0){
            f = usuario.getFolders().get(filaSelec);
            ef.eliminarFolder(f);
            usuario.getFolders().remove(filaSelec);
            setFolders();
        }
        
    }//GEN-LAST:event_elimFoldLblMouseClicked

    private void editFoldLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editFoldLblMouseClicked
        VentanaEdicionFolder ventana;
        Folder folder;
        int filaSelec;
        
        filaSelec   = foldersTab.getSelectedRow();
        
        if(filaSelec >= 0){
            folder = usuario.getFolders().get(filaSelec);
            ventana = new VentanaEdicionFolder(usuario.getUsuario(), usuario.getContM(), folder, this);
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_editFoldLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFolders(new Usuario("Juanito", "JuanitoContraseña")).setVisible(true);
            }
        });
    }
    
    private void setTable(){
        foldersTab.getTableHeader().setBackground(new Color(255,255,255));
        foldersTab.getTableHeader().setForeground(Color.BLACK);
        foldersTab.setRowHeight(30);
    }
    
    private void setUsrInfo(){
        usrInfoLbl.setText(usuario.getUsuario());
    }
    
    public void setFolders(){
        ArrayList<Folder> folders;
        DefaultTableModel modelo;
        Object[]          fila;
        
        folders = usuario.getFolders();
        
        
        
        modelo  = (DefaultTableModel) foldersTab.getModel();
        modelo.setRowCount(0);
        
        for(Folder f : folders){
            fila    = new Object[2];
            fila[0] = f.getNomFolder();
            fila[1] = f.getDescFolder();
            modelo.addRow(fila);
            
        }
    }
    
    private void setLookAndFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFolders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFolders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFolders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFolders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg2;
    private javax.swing.JPanel crearFoldBtn;
    private javax.swing.JLabel crearFoldLbl;
    private javax.swing.JPanel editFoldBtn;
    private javax.swing.JLabel editFoldLbl;
    private javax.swing.JPanel elimFoldBtn;
    private javax.swing.JLabel elimFoldLbl;
    private javax.swing.JPanel exitB;
    private javax.swing.JLabel exitLbl;
    private javax.swing.JPanel foldPanel;
    private javax.swing.JLabel foldersLbl;
    private javax.swing.JScrollPane foldersSP;
    private javax.swing.JTable foldersTab;
    private javax.swing.JLabel reloadLbl;
    private javax.swing.JPanel reloadPanel;
    private javax.swing.JPanel usrInfo;
    private javax.swing.JLabel usrInfoLbl;
    private javax.swing.JPanel verFoldBtn;
    private javax.swing.JLabel verFoldLbl;
    // End of variables declaration//GEN-END:variables
}
