/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jairo.gest.gui;


import com.jairo.gest.creadores.CreadorFolder;
import com.jairo.gest.usuarios.Usuario;
import java.awt.Color;


/**
 *
 * @author Jairo
 */
public class VentanaCreaFolder extends javax.swing.JFrame {

    private CreadorFolder creador;
    private VentanaFolders origen;
    private int mouseX, mouseY;
    public VentanaCreaFolder(Usuario usuario, VentanaFolders origen) {
        setLookAndFeel();
        initComponents();
        
        creador = new CreadorFolder(usuario);
        this.origen = origen;
        setUsrInfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        bg2 = new javax.swing.JPanel();
        creaPanel = new javax.swing.JPanel();
        creaLbl = new javax.swing.JLabel();
        nomFoldLbl = new javax.swing.JLabel();
        nomFoldTxtBox = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        descFoldLbl = new javax.swing.JLabel();
        descFoldTxtBox = new javax.swing.JTextField();
        usrInfo = new javax.swing.JPanel();
        usrInfoLbl = new javax.swing.JLabel();
        crearFoldBtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mensajeLbl = new javax.swing.JLabel();
        bar = new javax.swing.JPanel();
        exitB = new javax.swing.JPanel();
        exitLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(203, 182, 184));
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bg.setPreferredSize(new java.awt.Dimension(737, 467));

        bg2.setBackground(new java.awt.Color(31, 31, 31));

        creaPanel.setBackground(new java.awt.Color(255, 255, 255));
        creaPanel.setFocusable(false);
        creaPanel.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N

        creaLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        creaLbl.setText("Creación de Folder");

        nomFoldLbl.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        nomFoldLbl.setText("Nombre del folder");

        nomFoldTxtBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nomFoldTxtBox.setForeground(new java.awt.Color(204, 204, 204));
        nomFoldTxtBox.setText("Nombre del folder");
        nomFoldTxtBox.setBorder(null);
        nomFoldTxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomFoldTxtBoxFocusGained(evt);
            }
        });
        nomFoldTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFoldTxtBoxActionPerformed(evt);
            }
        });

        separador1.setForeground(new java.awt.Color(0, 0, 0));

        separador2.setForeground(new java.awt.Color(0, 0, 0));

        descFoldLbl.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        descFoldLbl.setText("Descripción del folder (Opcional)");

        descFoldTxtBox.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        descFoldTxtBox.setForeground(new java.awt.Color(204, 204, 204));
        descFoldTxtBox.setText("Descripción del folder");
        descFoldTxtBox.setBorder(null);
        descFoldTxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descFoldTxtBoxFocusGained(evt);
            }
        });
        descFoldTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descFoldTxtBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout creaPanelLayout = new javax.swing.GroupLayout(creaPanel);
        creaPanel.setLayout(creaPanelLayout);
        creaPanelLayout.setHorizontalGroup(
            creaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creaPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(creaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(descFoldLbl)
                        .addComponent(descFoldTxtBox)
                        .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(creaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nomFoldLbl)
                        .addComponent(creaLbl)
                        .addComponent(nomFoldTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                        .addComponent(separador1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        creaPanelLayout.setVerticalGroup(
            creaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(creaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomFoldLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomFoldTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descFoldLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descFoldTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        usrInfo.setBackground(new java.awt.Color(255, 255, 255));

        usrInfoLbl.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        usrInfoLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usrInfoLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jairo\\Documents\\NetBeansProjects\\GestorContrasenias\\src\\main\\java\\com\\jairo\\gest\\gui\\assets\\User.png")); // NOI18N
        usrInfoLbl.setText("Usuario");

        javax.swing.GroupLayout usrInfoLayout = new javax.swing.GroupLayout(usrInfo);
        usrInfo.setLayout(usrInfoLayout);
        usrInfoLayout.setHorizontalGroup(
            usrInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usrInfoLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(usrInfoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        usrInfoLayout.setVerticalGroup(
            usrInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usrInfoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        crearFoldBtn.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Folder");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crearFoldBtnLayout = new javax.swing.GroupLayout(crearFoldBtn);
        crearFoldBtn.setLayout(crearFoldBtnLayout);
        crearFoldBtnLayout.setHorizontalGroup(
            crearFoldBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        crearFoldBtnLayout.setVerticalGroup(
            crearFoldBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        mensajeLbl.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        mensajeLbl.setForeground(new java.awt.Color(255, 255, 255));
        mensajeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensajeLbl.setText("Mensaje");

        javax.swing.GroupLayout bg2Layout = new javax.swing.GroupLayout(bg2);
        bg2.setLayout(bg2Layout);
        bg2Layout.setHorizontalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addComponent(usrInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mensajeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(crearFoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(creaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        bg2Layout.setVerticalGroup(
            bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg2Layout.createSequentialGroup()
                .addGroup(bg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(usrInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensajeLbl)
                        .addGap(20, 20, 20)))
                .addComponent(creaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crearFoldBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bar.setBackground(new java.awt.Color(203, 182, 184));
        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });

        exitB.setBackground(new java.awt.Color(203, 182, 184));
        exitB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBMouseExited(evt);
            }
        });

        exitLbl.setBackground(new java.awt.Color(203, 182, 184));
        exitLbl.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        exitLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLbl.setText("X");
        exitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBLayout = new javax.swing.GroupLayout(exitB);
        exitB.setLayout(exitBLayout);
        exitBLayout.setHorizontalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
        exitBLayout.setVerticalGroup(
            exitBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addContainerGap(724, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(exitB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX , y - mouseY );
    }//GEN-LAST:event_barMouseDragged

    private void exitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitLblMouseClicked

    private void exitLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseEntered
        exitB.setBackground(new Color(210, 51, 105));
    }//GEN-LAST:event_exitLblMouseEntered

    private void exitBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseExited
        exitB.setBackground(new Color(203, 182, 184));
    }//GEN-LAST:event_exitBMouseExited

    private void exitBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBMouseEntered
        exitB.setBackground(new Color(210, 51, 105));
    }//GEN-LAST:event_exitBMouseEntered

    private void exitLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLblMouseExited
        exitB.setBackground(new Color(203, 182, 184));
    }//GEN-LAST:event_exitLblMouseExited

    private void nomFoldTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFoldTxtBoxActionPerformed
        
    }//GEN-LAST:event_nomFoldTxtBoxActionPerformed

    private void descFoldTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descFoldTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descFoldTxtBoxActionPerformed

    private void nomFoldTxtBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFoldTxtBoxFocusGained
        
        if(descFoldTxtBox.getText().equals("Descripción del folder")){
            descFoldTxtBox.setText("");
        }
        if(nomFoldTxtBox.getText().equals("Nombre del folder")){
            nomFoldTxtBox.setText("");
        }
        
        nomFoldTxtBox.setForeground(Color.black);
        descFoldTxtBox.setForeground(Color.black);
        mensajeLbl.setVisible(false);
    }//GEN-LAST:event_nomFoldTxtBoxFocusGained

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(verificarLlenado()){
            if(creador.crearFolder(nomFoldTxtBox.getText(), descFoldTxtBox.getText())){
                mensajeLbl.setText("Folder creado exitosamente");
                origen.setFolders();
            }else{
                mensajeLbl.setText("Error al crear el folder");
            }
            mensajeLbl.setVisible(true);
        }
             
    }//GEN-LAST:event_jLabel1MouseClicked

    private void descFoldTxtBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descFoldTxtBoxFocusGained
        if(descFoldTxtBox.getText().equals("Descripción del folder")){
            descFoldTxtBox.setText("");
        }
        if(nomFoldTxtBox.getText().equals("Nombre del folder")){
            nomFoldTxtBox.setText("");
        }
        
        nomFoldTxtBox.setForeground(Color.black);
        descFoldTxtBox.setForeground(Color.black);
        mensajeLbl.setVisible(false);
    }//GEN-LAST:event_descFoldTxtBoxFocusGained

    private boolean verificarLlenado(){
        boolean correcto;
        String  mensaje;
        
        mensaje = null;
        if(nomFoldTxtBox.getText().equals("") || nomFoldTxtBox.getText().equals("Nombre del folder")){
           mensaje = "Debe introducir un nombre para el folder";
        }
        
        correcto = mensaje == null;
        
        if(mensaje != null){
            mensajeLbl.setText(mensaje);
            mensajeLbl.setVisible(true);
        }
        
        return correcto;
       
    }
    
    private void setUsrInfo(){
        usrInfoLbl.setText(creador.getUsuario().getUsuario());
    }
    

    
    private void setLookAndFeel(){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCreaFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCreaFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCreaFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCreaFolder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg2;
    private javax.swing.JLabel creaLbl;
    private javax.swing.JPanel creaPanel;
    private javax.swing.JPanel crearFoldBtn;
    private javax.swing.JLabel descFoldLbl;
    private javax.swing.JTextField descFoldTxtBox;
    private javax.swing.JPanel exitB;
    private javax.swing.JLabel exitLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mensajeLbl;
    private javax.swing.JLabel nomFoldLbl;
    private javax.swing.JTextField nomFoldTxtBox;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JPanel usrInfo;
    private javax.swing.JLabel usrInfoLbl;
    // End of variables declaration//GEN-END:variables
}
